server:
 port: 8082

eureka:
 client:
  serviceUrl:
   defaultZone: "http://localhost:8085/eureka"
   
spring:   
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: update
  database-platform: "org.hibernate.dialect.MySQL8Dialect"

 datasource:
  username: root
  password: admin
  url: "jdbc:mysql://localhost:3306/employeedb?createDatabaseIfNotExist=true"
  driverClassName: com.mysql.cj.jdbc.Driver

management:
 tracing:
  sampling:
   probability: 1.0