server:
 port: 8090

spring:
 application:
  name: todo
 
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: update
 datasource:
  url: jdbc:mysql://localhost:3306/todoapp?createDatabaseIfNotExist=true
  driverClassName: com.mysql.cj.jdbc.Driver
  username: root
  password: admin