spring:
 dataSource:
  url: jdbc:h2:mem:hotel_sarvice_database
  platform: h2
  username: sa
  password:
  driverClassName: org.h2.Driver
  
 h2:
  console:
   enabled: true
   path: /h2-console
 
 jpa:
  hibernate:
   ddl-auto: update
   generate-ddl: true
   database-platform: org.hibernate.dialect.H2Dialect

server:
 port: 8085